name: weather_app
description: "A Flutter weather application using OpenWeatherMap API."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0 # Added for API calls
  flutter_dotenv: ^5.1.0 # Added for secure API key storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env # Environment file for API keys
